#mysql
connect: root:123456@tcp(127.0.0.1:3306)/ad_test?charset=utf8&multiStatements=true
connectType: mysql
maxIdleConns: 100
maxOpenConns: 100
connMaxLifetime: 5                #默认最大值为10
pagesize: 20

#日志文件
loglevel: debug                   # debug   info   error
hookMaxSize: 1024                 #每个日志文件保存的最大尺寸 单位：M
hookMaxBackups: 3                 #日志文件最多保存多少个备份
hookMaxAge: 30                    #文件最多保存多少天
hookCompress: true                #是否压缩
logSavePath: runtime/logs/err/    #log保存路径

#系统相关
serviceName: goApiFrame           #服务名
port: 6004                        #web端口
host: 127.0.0.1
#debug or release
runMode: debug


#捕获异常邮件设置
sendEmail: true
fromEmailUserName: admin@123.com  #发件人邮箱
emailPass: 123456  #邮箱密码
toEmailUser: tom@123.com   #收件人，可以为多个，以逗号隔开
emailPort: 465                  #邮箱端口
emailSSL: true

#upload
imageSavePath: runtime/upload/images/
# MB
imageMaxSize: 5
imageAllowExts: .jpg,.png,.jpeg