#mysql
port: 6004
connect: root:123456@tcp(127.0.0.1:3306)/ad_test?charset=utf8&multiStatements=true
connectType: mysql

#日志文件
loglevel: debug                   # debug   info   error
hookMaxSize: 128                  #每个日志文件保存的最大尺寸 单位：M
hookFilename: ./logs/system.log   #日志文件路径
hookMaxBackups: 3                 #日志文件最多保存多少个备份
hookMaxAge: 30                    #文件最多保存多少天
hookCompress: true                #是否压缩
serviceName: goApiFrame           #服务名